/**
 * Template schema registry.
 *
 * Each entry declares:
 *   data          – required payload fields that must be present in the `data`
 *                   object sent by the caller.  Missing fields produce a 400.
 *   requireCtaPath – when true the `x-path` header (appContext.ctaPath) is
 *                   also required; missing it produces a 400.
 *
 * Optional / cosmetic fields (appUrl, applicationName, ctaUrl, etc.) are
 * handled by the service-level enrichment and are NOT listed here.
 *
 * To add a new template: append an entry in the appropriate section.
 */
export interface TemplateSchema {
  data: string[];
  requireCtaPath?: boolean;
}

export const TEMPLATE_SCHEMAS: Record<string, TemplateSchema> = {

  // ── OTP / Email Verification ──────────────────────────────────────────────
  otpEmailTemplate:                            { data: ['otp'] },
  otpForLoginTemplate:                         { data: ['username', 'otp'] },
  EMAIL_VERIFICATION_SEND:                     { data: ['username', 'token'] },
  USER_EMAIL_VERIFIED:                         { data: ['username'] },

  // ── User Lifecycle ────────────────────────────────────────────────────────
  USER_CREATED:                                { data: ['userId', 'username', 'email', 'timestamp'] },
  USER_WELCOME:                                { data: ['userId', 'username', 'email', 'verifyLink', 'timestamp'] },
  ADMIN_USER_REGISTERED:                       { data: ['userId', 'username', 'email', 'registeredAt'] },
  USER_UPDATED:                                { data: ['userId', 'username', 'email', 'timestamp'] },
  USER_DELETED:                                { data: ['userId', 'username', 'email', 'timestamp'] },
  USER_SUSPENDED:                              { data: ['userId', 'username', 'email', 'timestamp'] },
  USER_BANNED:                                 { data: ['userId', 'username', 'email', 'timestamp'] },
  USER_REINSTATED:                             { data: ['userId', 'username', 'email', 'timestamp'] },
  accountDeletedTemplate:                      { data: ['username'] },

  // ── Roles & Permissions ───────────────────────────────────────────────────
  ROLE_ASSIGNED:                               { data: ['username', 'roleName'] },
  ROLE_REVOKED:                                { data: ['username', 'roleName'] },
  PERMISSION_CHANGED:                          { data: ['username'] },

  // ── Password ──────────────────────────────────────────────────────────────
  PASSWORD_CHANGED:                            { data: ['username'] },
  PASSWORD_RESET_REQUESTED:                    { data: ['resetLink'] },
  PASSWORD_RESET_COMPLETED:                    { data: ['username'] },
  PASSWORD_EXPIRED:                            { data: ['username'] },
  passwordExpiryReminderTemplate:              { data: ['username', 'resetLink'] },

  // ── Profile / Phone ───────────────────────────────────────────────────────
  PHONE_VERIFIED:                              { data: ['username'] },
  PROFILE_COMPLETED:                           { data: ['username'] },
  PROFILE_PICTURE_UPDATED:                     { data: ['username'] },
  phoneVerificationTemplate:                   { data: ['username', 'phone', 'verificationCode'] },
  secondaryPhoneVerificationTemplate:          { data: ['username', 'verificationCode'] },
  phoneNumberChangeRequestTemplate:            { data: ['username', 'newPhone', 'confirmationCode'] },
  phoneNumberChangeConfirmationTemplate:       { data: ['username', 'updatedPhone'] },
  emailPhoneVerificationReminderTemplate:      { data: ['username'] },

  // ── Login / Security ──────────────────────────────────────────────────────
  LOGIN_SUCCESS:                               { data: ['username', 'ipAddress', 'timestamp'] },
  LOGIN_FAILED:                                { data: ['username'] },
  NEW_DEVICE_LOGIN:                            { data: ['username', 'device', 'timestamp'] },
  ACCOUNT_LOCKED:                              { data: ['username'] },
  ACCOUNT_UNLOCKED:                            { data: ['username'] },
  ACCOUNT_RECOVERY_REQUESTED:                  { data: ['username'] },
  ACCOUNT_RECOVERY_COMPLETED:                  { data: ['username'] },
  MFA_ENABLED:                                 { data: ['username', 'device', 'timestamp'] },
  MFA_DISABLED:                                { data: ['username', 'device', 'timestamp'], requireCtaPath: true },
  SESSION_EXPIRED:                             { data: ['username', 'device', 'timestamp'], requireCtaPath: true },
  loginAlertTemplate:                          { data: ['username', 'device', 'location', 'time'] },
  logoutAllDevicesTemplate:                    { data: ['username', 'timestamp'], requireCtaPath: true },
  failedLoginAttemptsTemplate:                 { data: ['username', 'attempts'] },
  failedLoginAttemptWarningTemplate:           { data: ['username', 'attempts'] },
  loginAttemptLimitExceededTemplate:           { data: ['username'] },
  trustedDeviceAddedTemplate:                  { data: ['username', 'device', 'location'] },
  backupCodesTemplate:                         { data: ['username', 'codes'] },
  accountVerificationReminderTemplate:         { data: ['username'] },
  trustedDeviceManagementUpdateTemplate:       { data: ['username'] },
  multiFactorAuthenticationSetupReminderTemplate: { data: ['username'] },
  twoFactorEnabledDisabledNotificationTemplate: { data: ['username', 'status'] },
  twoFactorCompletedTemplate:                  { data: ['username'] },
  accountSecurityCheckReminderTemplate:        { data: ['username'] },
  sessionTimeoutNotificationTemplate:          { data: ['username'] },
  fraudulentTransactionAlertTemplate:          { data: ['username', 'transactionId', 'amount'] },

  // ── Account State ─────────────────────────────────────────────────────────
  CONSENT_REQUIRED:                            { data: ['username', 'consentType'], requireCtaPath: true },
  CONSENT_REVOKED:                             { data: ['username', 'consentType'] },
  ACCOUNT_MERGED:                              { data: ['username', 'accountId', 'reason'] },
  ACCOUNT_TERMINATED:                          { data: ['username', 'accountId', 'reason'] },
  SOCIAL_LOGIN_CONNECTED:                      { data: ['username', 'provider', 'timestamp'], requireCtaPath: true },
  SOCIAL_LOGIN_DISCONNECTED:                   { data: ['username', 'provider', 'timestamp'], requireCtaPath: true },
  accountReactivationTemplate:                 { data: ['username', 'reactivateLink'] },
  accountSuspendedTemplate:                    { data: ['username', 'reason'] },
  consentRequiredTemplate:                     { data: ['username', 'consentLink'] },
  securitySettingsUpdatedTemplate:             { data: ['username', 'setting'] },
  accountAccessRevokedTemplate:                { data: ['username'] },
  passwordStrengthWarningTemplate:             { data: ['username'] },
  accountMergeConfirmationTemplate:            { data: ['username'], requireCtaPath: true },
  socialLoginConnectionTemplate:               { data: ['username', 'action'] },
  identityVerificationRequestTemplate:         { data: ['username'] },
  identityVerificationResultTemplate:          { data: ['username', 'result'] },
  backupEmailAddedRemovedTemplate:             { data: ['username', 'action'] },
  emailChangedTemplate:                        { data: ['username', 'oldEmail', 'newEmail'] },

  // ── Policy ────────────────────────────────────────────────────────────────
  PRIVACY_POLICY_UPDATED:                      { data: ['effectiveDate'], requireCtaPath: true },
  TERMS_OF_SERVICE_UPDATED:                    { data: ['effectiveDate'], requireCtaPath: true },

  // ── Organisation ──────────────────────────────────────────────────────────
  CONTACT_NOTIFICATION:                        { data: ['name', 'email', 'subject', 'message'] },
  ORG_CREATED:                                 { data: ['orgName', 'adminName'] },
  ORG_UPDATED:                                 { data: ['orgName', 'updatedBy'] },
  ORG_DELETED:                                 { data: ['orgName', 'deletedBy'] },
  ORG_PLAN_CHANGED:                            { data: ['orgName', 'oldPlan', 'newPlan'] },
  ORG_MEMBER_INVITED:                          { data: ['orgName', 'inviteeEmail', 'invitedBy', 'inviteUrl'] },
  ORG_MEMBER_REMOVED:                          { data: ['orgName', 'memberName'], requireCtaPath: true },
  ORG_ROLE_ASSIGNED:                           { data: ['orgName', 'memberName', 'roleName'] },
  ORG_ROLE_CHANGED:                            { data: ['orgName', 'memberName', 'oldRole', 'newRole'] },
  ORG_ROLE_REVOKED:                            { data: ['orgName', 'memberName', 'roleName'] },
  ORG_SECURITY_POLICY_UPDATED:                 { data: ['orgName', 'updatedBy'] },
  ORG_API_KEY_CREATED:                         { data: ['orgName', 'keyName', 'createdBy'] },
  ORG_API_KEY_REVOKED:                         { data: ['orgName', 'keyName', 'revokedBy'] },
  ORG_DOMAIN_VERIFIED:                         { data: ['orgName', 'domain'] },
  ORG_DOMAIN_UNVERIFIED:                       { data: ['orgName', 'domain'], requireCtaPath: true },
  ORG_BILLING_UPDATED:                         { data: ['orgName', 'updatedBy'] },
  ORG_COMPLIANCE_AUDIT_COMPLETED:              { data: ['orgName', 'auditType', 'status'] },
  TEAM_INVITE:                                 { data: ['inviteeEmail', 'invitedBy', 'teamName'] },

  // ── Newsletter / Welcome ──────────────────────────────────────────────────
  NEWSLETTER_WELCOME:                          { data: ['email', 'companyName'] },
  newsletterTemplate:                          { data: ['title', 'content'] },

  // ── Subscription / Payment (camelCase) ────────────────────────────────────
  subscriptionUpdatedTemplate:                 { data: ['username', 'plan'] },
  subscriptionStartedTemplate:                 { data: ['username', 'subscriptionName', 'startDate'] },
  subscriptionRenewedSuccessfullyTemplate:     { data: ['username', 'subscriptionName'] },
  subscriptionFailedRetryNeededTemplate:       { data: ['username', 'subscriptionName'] },
  subscriptionCanceledTemplate:                { data: ['username', 'subscriptionName'] },
  subscriptionPauseConfirmationTemplate:       { data: ['username', 'subscriptionName'], requireCtaPath: true },
  paymentSuccessfulTemplate:                   { data: ['username', 'orderId', 'amount'] },
  paymentMethodExpiringSoonTemplate:           { data: ['username', 'expiryDate'] },
  paymentMethodUpdatedTemplate:                { data: ['username'] },
  paymentDisputeNotificationTemplate:          { data: ['username', 'orderId'] },
  paymentDisputeResolvedTemplate:              { data: ['username', 'orderId'] },
  creditNoteIssuedTemplate:                    { data: ['username', 'creditNoteNumber', 'amount', 'issueDate'] },
  giftCardPurchasedTemplate:                   { data: ['username', 'giftCardCode', 'amount'] },
  giftCardRedeemedTemplate:                    { data: ['username', 'giftCardCode', 'amount'] },
  giftCardReceivedTemplate:                    { data: ['username', 'sender', 'amount', 'redeemCode'] },
  storeCreditAddedTemplate:                    { data: ['username', 'amount'] },
  storeCreditUsedTemplate:                     { data: ['username', 'amount'] },
  emiPaymentReminderTemplate:                  { data: ['username', 'dueDate'] },

  // ── Wishlist / Cart (camelCase) ───────────────────────────────────────────
  wishlistReminderTemplate:                    { data: ['username', 'wishlistItems'] },
  wishlistBackInStockTemplate:                 { data: ['username', 'itemName'] },
  wishlistPriceDropAlertTemplate:              { data: ['username', 'itemName', 'newPrice'] },
  wishlistItemDiscontinuedTemplate:            { data: ['username', 'itemName'] },
  savedForLaterReminderTemplate:               { data: ['username', 'savedItems'] },
  cartItemPriceChangedTemplate:                { data: ['username', 'itemName', 'oldPrice', 'newPrice'] },
  cartExpiryNotificationTemplate:              { data: ['username'] },

  // ── Orders (camelCase) ────────────────────────────────────────────────────
  orderProcessingTemplate:                     { data: ['username', 'orderId'] },
  orderPackedTemplate:                         { data: ['username', 'orderId'] },
  orderOutForDeliveryTemplate:                 { data: ['username', 'orderId'] },
  partialOrderShippedTemplate:                 { data: ['username', 'orderId'] },
  orderSplitShipmentTemplate:                  { data: ['username', 'orderId'] },
  deliveryDelayedNotificationTemplate:         { data: ['username', 'orderId'] },
  orderCanceledByCustomerTemplate:             { data: ['username', 'orderId'] },
  orderCanceledByStoreTemplate:                { data: ['username', 'orderId', 'reason'] },
  preOrderConfirmationTemplate:                { data: ['username', 'productName', 'releaseDate'] },
  preOrderShippedTemplate:                     { data: ['username', 'productName'] },
  digitalDownloadReadyTemplate:                { data: ['username', 'downloadLink'] },
  customOrderConfirmedTemplate:                { data: ['username'] },
  orderModificationRequestReceivedTemplate:    { data: ['username', 'orderId'] },
  orderModificationResultTemplate:             { data: ['username', 'orderId', 'status'] },
  returnRequestReceivedTemplate:               { data: ['username', 'orderId'] },
  returnApprovedTemplate:                      { data: ['username', 'orderId', 'instructions'] },
  returnRejectedTemplate:                      { data: ['username', 'orderId', 'reason'] },
  refundProcessedTemplate:                     { data: ['username', 'orderId'] },
  exchangeApprovedTemplate:                    { data: ['username', 'orderId', 'nextSteps'] },
  exchangeRejectedTemplate:                    { data: ['username', 'orderId', 'reason'] },
  returnShipmentReceivedTemplate:              { data: ['username', 'orderId'] },
  partialRefundProcessedTemplate:              { data: ['username', 'orderId', 'details'] },

  // ── Loyalty / Marketing (camelCase) ───────────────────────────────────────
  loyaltyPointsEarnedTemplate:                 { data: ['username', 'points'] },
  loyaltyPointsRedeemedTemplate:               { data: ['username', 'points'] },
  loyaltyPointsExpiryReminderTemplate:         { data: ['username'] },
  loyaltyTierChangeTemplate:                   { data: ['username', 'change'] },
  referralInvitationTemplate:                  { data: ['username'] },
  referralBonusEarnedTemplate:                 { data: ['username', 'bonus'] },
  referralBonusUsedTemplate:                   { data: ['username', 'bonus'] },
  dataExportRequestTemplate:                   { data: ['username', 'requestDate'] },
  trialExpiredTemplate:                        { data: ['username', 'upgradeLink'] },
  newFeatureAnnouncementTemplate:              { data: ['username', 'featureName'] },
  onboardingSeriesTemplate:                    { data: ['username'] },
  customerMilestoneTemplate:                   { data: ['username', 'period'] },
  seasonalSaleAnnouncementTemplate:            { data: ['username'] },
  flashSaleTemplate:                           { data: ['username'] },
  earlyAccessToSaleTemplate:                   { data: ['username'] },
  sneakPeekTemplate:                           { data: ['username'] },
  exclusiveEventTemplate:                      { data: ['username'] },
  surveyRequestTemplate:                       { data: ['username'] },
  holidayGreetingsTemplate:                    { data: ['username'] },
  csrStoriesTemplate:                          { data: ['username'] },
  appDownloadInvitationTemplate:               { data: ['username'], requireCtaPath: true },
  abandonedBrowseReminderTemplate:             { data: ['username', 'items'] },

  // ── System / Maintenance (camelCase) ─────────────────────────────────────
  systemMaintenanceNotificationTemplate:       { data: ['username', 'startTime', 'endTime'] },
  scheduledDowntimeNotificationTemplate:       { data: ['username', 'downtimeStart', 'downtimeEnd'] },

  // ── Admin Templates ───────────────────────────────────────────────────────
  newOrderPlacedAdminTemplate:                           { data: ['adminName', 'orderId', 'customerName', 'total'] },
  highValueOrderAlertAdminTemplate:                      { data: ['adminName', 'orderId', 'amount'] },
  lowStockAlertAdminTemplate:                            { data: ['adminName', 'productId', 'productName', 'currentStock'] },
  outOfStockNotificationAdminTemplate:                   { data: ['adminName', 'productId', 'productName'] },
  productDisabledAdminTemplate:                          { data: ['adminName', 'productId', 'productName'] },
  newReviewSubmittedAdminTemplate:                       { data: ['adminName', 'productName', 'reviewId'], requireCtaPath: true },
  paymentDisputeAlertAdminTemplate:                      { data: ['adminName', 'orderId'] },
  returnRequestNotificationAdminTemplate:                { data: ['adminName', 'orderId'] },
  refundProcessedNotificationAdminTemplate:              { data: ['adminName', 'orderId'] },
  dailySalesReportAdminTemplate:                         { data: ['adminName', 'reportDate', 'totalSales'] },
  weeklyMonthlySalesReportAdminTemplate:                 { data: ['adminName', 'period', 'totalSales'] },
  systemErrorFailedJobAlertAdminTemplate:                { data: ['adminName', 'errorDetails'] },
  customerSupportTicketCreatedAdminTemplate:             { data: ['adminName', 'ticketId', 'customerName'] },
  inventoryRestockNotificationAdminTemplate:             { data: ['adminName', 'productName', 'productId'] },
  bulkOrderRequestAdminTemplate:                         { data: ['adminName', 'requestId', 'requesterName'] },
  customerDataDeletionRequestAdminTemplate:              { data: ['adminName', 'userName', 'userId'] },
  suspiciousAccountActivityAlertAdminTemplate:           { data: ['adminName', 'userName', 'userId', 'details'] },
  multipleFailedLoginAttemptsAdminTemplate:              { data: ['adminName', 'userName', 'userId', 'attempts'] },
  accountSuspensionReinstatementNotificationAdminTemplate: { data: ['adminName', 'userName', 'userId', 'action'] },
  userProfileUpdateAlertAdminTemplate:                   { data: ['adminName', 'userName', 'userId', 'changes'] },
  twoFactorStatusChangeAlertAdminTemplate:               { data: ['adminName', 'userName', 'userId', 'status'] },
  accountDeletionRequestDeniedAdminTemplate:             { data: ['adminName', 'userName', 'userId', 'reason'] },
  unusualAccountLoginPatternAdminTemplate:               { data: ['adminName', 'userName', 'userId', 'details'] },
  phoneVerificationStatusUpdateAdminTemplate:            { data: ['adminName', 'userName', 'userId', 'status'] },
  emailVerificationFailureAlertAdminTemplate:            { data: ['adminName', 'userName', 'userId', 'attempts'] },
  secondaryPhoneVerificationStatusUpdateAdminTemplate:   { data: ['adminName', 'userName', 'userId', 'status'] },
  identityVerificationRequestReceivedAdminTemplate:      { data: ['adminName', 'userName', 'userId'] },
  identityVerificationOutcomeNotificationAdminTemplate:  { data: ['adminName', 'userName', 'userId', 'result'] },
  accountAccessRevocationAdminTemplate:                  { data: ['adminName', 'userName', 'userId'] },
  socialLoginConnectionAlertAdminTemplate:               { data: ['adminName', 'userName', 'userId', 'action'] },
  accountMergeRequestReceivedAdminTemplate:              { data: ['adminName', 'userName', 'userId'] },
  highRiskAccountActivityAlertAdminTemplate:             { data: ['adminName', 'userName', 'userId', 'details'] },
  accountRecoveryRequestReceivedAdminTemplate:           { data: ['adminName', 'userName', 'userId'] },
  fraudulentActivityDetectedAdminTemplate:               { data: ['adminName', 'userName', 'userId', 'activityDetails'] },

  // ── Payments (UPPERCASE) ──────────────────────────────────────────────────
  PAYMENT_SUCCESS:                             { data: ['username', 'amount', 'transactionId'] },
  PAYMENT_FAILED:                              { data: ['username', 'amount', 'transactionId', 'failureReason'] },
  PAYMENT_PENDING:                             { data: ['username', 'amount', 'paymentMethod'] },
  PAYMENT_REFUNDED:                            { data: ['username', 'amount', 'transactionId', 'refundId'] },
  INVOICE_GENERATED:                           { data: ['username', 'invoiceNumber', 'dueDate', 'amount'] },
  INVOICE_PAID:                                { data: ['username', 'invoiceNumber', 'amount'] },
  INVOICE_OVERDUE:                             { data: ['username', 'invoiceNumber', 'dueDate', 'amount'] },
  INVOICE_CANCELLED:                           { data: ['username', 'invoiceNumber'] },
  BILLING_INFO_UPDATED:                        { data: ['username', 'updatedFields', 'updatedAt'] },
  AUTO_RENEWAL_REMINDER:                       { data: ['username', 'subscriptionName', 'renewalDate', 'amount'] },
  SUBSCRIPTION_STARTED:                        { data: ['username', 'subscriptionName', 'startDate'] },
  SUBSCRIPTION_CANCELLED:                      { data: ['username', 'subscriptionName', 'cancelledAt'] },
  SUBSCRIPTION_RENEWED:                        { data: ['username', 'subscriptionName', 'renewalDate', 'amount'] },
  CHARGEBACK_INITIATED:                        { data: ['username', 'transactionId', 'amount', 'reason'] },
  CHARGEBACK_RESOLVED:                         { data: ['username', 'transactionId', 'amount', 'outcome'] },

  // ── Cart / Wishlist (UPPERCASE) ───────────────────────────────────────────
  CART_CREATED:                                { data: ['username', 'cartId', 'itemCount'] },
  CART_UPDATED:                                { data: ['username', 'cartId', 'itemCount', 'totalAmount'] },
  CART_ABANDONED:                              { data: ['username', 'cartId', 'itemCount', 'totalAmount'] },
  WISHLIST_CREATED:                            { data: ['username', 'wishlistId', 'itemCount'] },
  WISHLIST_REMINDER:                           { data: ['username', 'wishlistId', 'itemCount', 'items'] },
  WISHLIST_PRICE_DROP:                         { data: ['username', 'productName', 'oldPrice', 'newPrice'] },
  WISHLIST_BACK_IN_STOCK:                      { data: ['username', 'productName', 'productId'] },
  CART_ITEM_PRICE_CHANGED:                     { data: ['username', 'cartId', 'productName', 'oldPrice', 'newPrice'] },
  CART_EXPIRY_NOTIFICATION:                    { data: ['username', 'cartId', 'itemCount', 'expiryDate'] },

  // ── Orders (UPPERCASE) ────────────────────────────────────────────────────
  ORDER_CREATED:                               { data: ['username', 'orderId', 'totalAmount'] },
  ORDER_CONFIRMED:                             { data: ['username', 'orderId', 'totalAmount'] },
  ORDER_SHIPPED:                               { data: ['username', 'orderId', 'trackingNumber', 'carrier'] },
  ORDER_DELIVERED:                             { data: ['username', 'orderId', 'deliveryDate'] },
  ORDER_DELAYED:                               { data: ['username', 'orderId', 'reason', 'newEstimatedDelivery'] },
  ORDER_CANCELLED:                             { data: ['username', 'orderId'] },
  ORDER_RETURNED:                              { data: ['username', 'orderId', 'returnReason'] },
  ORDER_REFUNDED:                              { data: ['username', 'orderId', 'refundAmount', 'refundMethod'] },
  ORDER_PAYMENT_PENDING:                       { data: ['username', 'orderId', 'amount', 'paymentMethod'] },
  ORDER_PAYMENT_FAILED:                        { data: ['username', 'orderId', 'amount', 'paymentMethod', 'failureReason'] },
  ORDER_PARTIALLY_SHIPPED:                     { data: ['username', 'orderId', 'trackingNumber'] },
  CUSTOM_ORDER_CONFIRMED:                      { data: ['username', 'orderId', 'customDetails', 'totalAmount'] },
  ORDER_REVIEWED:                              { data: ['username', 'orderId', 'rating'] },

  // ── Returns / Exchanges (UPPERCASE) ──────────────────────────────────────
  RETURN_REQUEST_RECEIVED:                     { data: ['username', 'orderId', 'returnId', 'returnReason'] },
  RETURN_APPROVED:                             { data: ['username', 'orderId', 'returnId'] },
  RETURN_REJECTED:                             { data: ['username', 'orderId', 'returnId', 'rejectionReason'] },
  RETURN_COMPLETED:                            { data: ['username', 'orderId', 'returnId', 'refundAmount', 'refundMethod'] },
  EXCHANGE_REQUESTED:                          { data: ['username', 'orderId', 'exchangeId', 'originalItem', 'requestedItem'] },
  EXCHANGE_APPROVED:                           { data: ['username', 'orderId', 'exchangeId', 'originalItem', 'newItem'] },
  EXCHANGE_REJECTED:                           { data: ['username', 'orderId', 'exchangeId', 'rejectionReason'] },

  // ── System / Infrastructure (UPPERCASE) ──────────────────────────────────
  SYSTEM_ALERT:                                { data: ['alertType', 'severity', 'message', 'detectedAt'] },
  MAINTENANCE_SCHEDULED:                       { data: ['maintenanceType', 'scheduledStart', 'scheduledEnd'] },
  MAINTENANCE_STARTED:                         { data: ['maintenanceType', 'startedAt', 'estimatedEnd'] },
  MAINTENANCE_COMPLETED:                       { data: ['maintenanceType', 'completedAt', 'duration'] },
  DATA_BACKUP_COMPLETED:                       { data: ['backupType', 'completedAt', 'status'] },
  SERVER_RESTARTED:                            { data: ['serverName', 'restartReason', 'restartedAt'] },
  SERVER_OVERLOADED:                           { data: ['serverName', 'cpuUsage', 'memoryUsage', 'detectedAt'] },
  DEPLOYMENT_STARTED:                          { data: ['version', 'environment', 'deployedBy', 'startedAt'] },
  DEPLOYMENT_COMPLETED:                        { data: ['version', 'environment', 'deployedBy', 'completedAt'] },
  DEPLOYMENT_FAILED:                           { data: ['version', 'environment', 'deployedBy', 'failedAt', 'errorMessage'] },
  CONFIGURATION_CHANGED:                       { data: ['configType', 'changedBy', 'changedAt', 'environment'] },
  SERVICE_OUTAGE_DETECTED:                     { data: ['serviceName', 'detectedAt', 'errorDetails'] },
  SERVICE_RECOVERED:                           { data: ['serviceName', 'recoveredAt', 'rootCause'] },
  NEW_FEATURE_RELEASED:                        { data: ['featureName', 'releaseDate', 'description'] },

  // ── Shipping / Packages (UPPERCASE) ──────────────────────────────────────
  PACKAGE_DISPATCHED:                          { data: ['username', 'orderId', 'trackingNumber'] },
  PACKAGE_IN_TRANSIT:                          { data: ['username', 'orderId', 'trackingNumber', 'estimatedDelivery', 'carrier'] },
  PACKAGE_OUT_FOR_DELIVERY:                    { data: ['username', 'orderId', 'trackingNumber', 'estimatedDelivery'] },
  PACKAGE_DELIVERED:                           { data: ['username', 'orderId', 'deliveredAt'] },
  PACKAGE_DELAYED:                             { data: ['username', 'orderId', 'trackingNumber', 'newDelivery', 'reason'] },
  PACKAGE_LOST:                                { data: ['username', 'orderId', 'trackingNumber'] },
  DELIVERY_EXCEPTION:                          { data: ['username', 'orderId', 'trackingNumber', 'exceptionType', 'details'] },
  CUSTOMS_HOLD:                                { data: ['username', 'orderId', 'trackingNumber', 'holdReason'] },

  // ── Promotions / Loyalty (UPPERCASE) ─────────────────────────────────────
  PROMOTION_LAUNCHED:                          { data: ['username', 'promotionName', 'discountPercentage', 'validFrom', 'validTo'] },
  DISCOUNT_APPLIED:                            { data: ['username', 'discountAmount', 'discountType'] },
  FLASH_SALE_ANNOUNCEMENT:                     { data: ['saleName', 'startsAt', 'endsAt', 'discount'] },
  LOYALTY_POINTS_EARNED:                       { data: ['username', 'pointsEarned', 'totalPoints', 'reason'] },
  LOYALTY_POINTS_REDEEMED:                     { data: ['username', 'pointsRedeemed', 'remainingPoints', 'redemptionValue'] },
  NEW_PRODUCT_LAUNCH:                          { data: ['username', 'productName', 'launchDate'] },
  CUSTOMER_MILESTONE:                          { data: ['username', 'milestoneType', 'milestoneValue'] },
  REVIEW_REMINDER:                             { data: ['username', 'productName', 'orderId'] },
  EVENT_INVITATION:                            { data: ['username', 'eventName', 'eventDate', 'eventTime', 'location'] },
  HOLIDAY_GREETINGS:                           { data: ['username', 'holidayName', 'greeting'] },

  // ── Products (UPPERCASE) ──────────────────────────────────────────────────
  PRODUCT_CREATED:                             { data: ['productName', 'productId', 'category'] },
  PRODUCT_UPDATED:                             { data: ['productName', 'productId', 'updatedFields', 'updatedBy'] },
  PRODUCT_DELETED:                             { data: ['productName', 'productId', 'deletedBy'] },
  PRODUCT_FEATURED:                            { data: ['productName', 'productId', 'featureType', 'startDate', 'endDate'] },
  PRODUCT_BACK_IN_STOCK:                       { data: ['username', 'productName', 'productId'] },
  PRODUCT_REVIEWED:                            { data: ['productName', 'productId', 'reviewerName', 'rating'] },
  PRODUCT_OUT_OF_STOCK:                        { data: ['productName', 'productId'] },
  PRODUCT_ARCHIVED:                            { data: ['productName', 'productId', 'archivedBy', 'reason'] },

  // ── Inventory (UPPERCASE) ─────────────────────────────────────────────────
  STOCK_LOW:                                   { data: ['productName', 'currentStock', 'minimumThreshold', 'productId'] },
  STOCK_CRITICAL:                              { data: ['productName', 'currentStock', 'criticalThreshold', 'productId'] },
  STOCK_REPLENISHED:                           { data: ['productName', 'quantityAdded', 'newStock'] },
  INVENTORY_AUDIT_COMPLETED:                   { data: ['auditType', 'completedAt'] },
  SUPPLIER_DELAY:                              { data: ['supplierName', 'orderId', 'originalDelivery', 'newDelivery'] },
  BATCH_EXPIRING_SOON:                         { data: ['productName', 'batchNumber', 'expiryDate', 'daysRemaining'] },
  WAREHOUSE_TRANSFER_INITIATED:                { data: ['transferId', 'fromWarehouse', 'toWarehouse', 'initiatedBy'] },

  // ── Messaging / Communication (UPPERCASE) ────────────────────────────────
  MESSAGE_SENT:                                { data: ['senderName', 'recipientName', 'messagePreview', 'sentAt'] },
  MESSAGE_RECEIVED:                            { data: ['recipientName', 'senderName', 'messagePreview', 'receivedAt'] },
  MESSAGE_READ:                                { data: ['senderName', 'recipientName', 'readAt'] },
  MENTION_RECEIVED:                            { data: ['username', 'mentionedBy', 'context', 'contentPreview'] },
  COMMENT_POSTED:                              { data: ['username', 'commenterName', 'contentType', 'commentPreview'] },
  COMMENT_REPLIED:                             { data: ['username', 'replyName', 'originalComment', 'replyContent'] },
  EMAIL_DELIVERED:                             { data: ['emailAddress', 'messageSubject', 'deliveredAt', 'deliveryStatus'] },
  EMAIL_FAILED:                                { data: ['emailAddress', 'messageSubject', 'failureReason', 'failedAt'] },
  PUSH_NOTIFICATION_SENT:                      { data: ['deviceType', 'notificationTitle', 'notificationBody', 'sentAt'] },
  CHAT_STARTED:                                { data: ['username', 'chatInitiator', 'topic', 'chatId'] },
  CHAT_ENDED:                                  { data: ['username', 'chatWith', 'topic', 'chatId'] },

  // ── Reports / Analytics (UPPERCASE) ──────────────────────────────────────
  DAILY_REPORT_READY:                          { data: ['username', 'reportDate', 'reportUrl'] },
  WEEKLY_REPORT_READY:                         { data: ['username', 'weekStart', 'weekEnd', 'reportUrl'] },
  MONTHLY_REPORT_READY:                        { data: ['username', 'month', 'year', 'reportUrl'] },
  DATA_TREND_ALERT:                            { data: ['username', 'trendType', 'metric', 'change'] },
  TRAFFIC_SPIKE:                               { data: ['username', 'spikePercentage', 'currentTraffic', 'normalTraffic'] },
  CONVERSION_RATE_DROP:                        { data: ['username', 'currentRate', 'previousRate', 'percentageDrop'] },
  ENGAGEMENT_INCREASED:                        { data: ['username', 'engagementMetric', 'increasePercentage', 'currentValue'] },
  KPI_THRESHOLD_BREACHED:                      { data: ['username', 'kpiName', 'currentValue', 'threshold'] },

  // ── Contact / Inquiry (UPPERCASE) ────────────────────────────────────────
  CONTACT_REPLY:                               { data: ['name', 'email', 'subject'] },
  INQUIRY_NOTIFICATION:                        { data: ['name', 'email', 'projectType'] },
  CONTACT_CONFIRMATION:                        { data: ['name', 'subject'] },
  INQUIRY_CONFIRMATION:                        { data: ['name', 'projectType', 'budget', 'timeline'] },

  // ── Special / Utility (UPPERCASE) ────────────────────────────────────────
  MAGIC_LINK:                                  { data: ['username', 'magicUrl'] },
  TRIAL_EXPIRING:                              { data: ['username', 'upgradeUrl'] },
  DATA_EXPORT_READY:                           { data: ['username', 'downloadUrl'] },
  BIRTHDAY_GREETING:                           { data: ['username'] },

  // ── Lead Management (UPPERCASE) ───────────────────────────────────────────
  LEAD_RECEIVED:                               { data: ['firstName', 'lastName', 'leadNumber', 'subject', 'projectType'] },
  LEAD_ADMIN_NOTIFICATION:                     { data: ['leadNumber', 'firstName', 'lastName', 'email'] },
  LEAD_CONTACT_REPLY:                          { data: ['firstName', 'lastName', 'leadNumber', 'subject', 'message'] },
  LEAD_STATUS_CHANGED:                         { data: ['firstName', 'lastName', 'leadNumber', 'oldStatus', 'newStatus'] },
  LEAD_FOLLOW_UP_REMINDER:                     { data: ['agentName', 'leadNumber', 'leadFirstName', 'leadLastName', 'leadEmail'] },
  PROJECT_PROPOSAL_EMAIL:                      { data: ['clientName', 'projectName', 'proposalUrl', 'proposalNumber'] },
  LEAD_PROPOSAL_ACCEPTED:                      { data: ['firstName', 'leadNumber', 'projectName', 'quotedAmount', 'agentName'] },
  LEAD_ADMIN_PROPOSAL_ACCEPTED:                { data: ['leadNumber', 'firstName', 'lastName', 'email', 'projectName'] },
  LEAD_PROPOSAL_DECLINED_ACK:                  { data: ['firstName', 'leadNumber', 'projectName', 'agentName'] },
  LEAD_ADMIN_PROPOSAL_DECLINED:                { data: ['leadNumber', 'firstName', 'lastName', 'email', 'declinedReason'] },
  LEAD_PROPOSAL_EXPIRING:                      { data: ['leadNumber', 'firstName', 'lastName', 'email', 'proposalNumber', 'validUntil'] },
  LEAD_PROPOSAL_EXPIRED:                       { data: ['leadNumber', 'firstName', 'lastName', 'email', 'proposalNumber', 'expiredAt'] },
  LEAD_CONTRACT_SENT:                          { data: ['firstName', 'leadNumber', 'projectName', 'contractUrl', 'agentName'] },
  LEAD_CONTRACT_SIGNED:                        { data: ['firstName', 'leadNumber', 'projectName', 'contractSignedAt', 'agentName'] },
  LEAD_WON_NOTIFICATION:                       { data: ['leadNumber', 'firstName', 'lastName', 'email', 'projectName'] },
  LEAD_LOST_NOTIFICATION:                      { data: ['leadNumber', 'firstName', 'lastName', 'email', 'lostReason'] },

  // ── Marketplace (UPPERCASE) ───────────────────────────────────────────────
  MARKETPLACE_WELCOME:                         { data: ['name'] },
  MARKETPLACE_EMAIL_VERIFICATION:              { data: ['name', 'verificationLink'] },
  MARKETPLACE_PASSWORD_RESET:                  { data: ['name', 'resetLink'] },
  MARKETPLACE_NEW_REQUEST:                     { data: ['providerName', 'requestTitle', 'category', 'budget', 'customerName'] },
  MARKETPLACE_PROPOSAL_RECEIVED:               { data: ['customerName', 'providerName', 'requestTitle', 'price'] },
  MARKETPLACE_JOB_ASSIGNED:                    { data: ['providerName', 'requestTitle', 'customerName', 'price', 'startDate'] },
  MARKETPLACE_PAYMENT_RECEIVED:                { data: ['providerName', 'amount', 'jobTitle', 'customerName'] },
  MARKETPLACE_PROVIDER_APPROVED:               { data: ['businessName', 'email'] },
  MARKETPLACE_PROVIDER_REJECTED:               { data: ['businessName', 'email', 'reason'] },
};
