name: Deploy Notification Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Install deps
      - name: Install dependencies
        run: npm install

      # 4. Build
      - name: Build project
        run: npm run build

      # 5. Upload to server
      - name: Upload files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: opc
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist,package.json,package-lock.json"
          target: "/home/opc/notification-service"

      # 6. Deploy (UPDATED PART)
      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: opc
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/opc/notification-service

            # install production deps (safe for low RAM)
            npm install --omit=dev --prefer-offline

            # start or restart with env update
            pm2 describe notification > /dev/null \
              && pm2 restart notification --update-env \
              || pm2 start dist/main.js --name notification --max-memory-restart 150M

            # save process list
            pm2 save